version: '3.8'

services:
  serial-executor:
    build: .
    volumes:
      - .:/app
    environment:
      - BAUD_RATE=115200
    devices:
      - "/dev/tty.usbmodem2101:/dev/tty.usbmodem2101"
    restart: unless-stopped
    privileged: true  # Allows the container to access devices dynamically
